spring:
  profiles:
    active: local

  datasource:
    url: jdbc:h2:tcp://localhost/~/noticeboard
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
#        use_sql_comments: true

logging.level:
  p6spy: info
  org.hibernate.SQL: debug
#  org.hibernate.type: trace